
global:
  version: "0.1.0"
  namespace: dev

ingress:
  className: ""
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          serviceName: frontend-service
          servicePort: 3000
        - path: /api
          pathType: Prefix
          serviceName: backend-service
          servicePort: 5000
