apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-nginx-ingress" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels: 
    {{- .Values.ingress.labels | toYaml | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end}}
spec: 
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}    
    {{- end }}
