apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret.name | quote }}
type: {{ .Values.db.secret.type | default "Opaque" }}
data:
  {{- range $key, $value := .Values.db.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
