{{- range $name, $config := .Values.rbac }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $config.namespace | default $.Release.Namespace }}
  name: {{ $name }}
rules:
{{- range $config.rules }}
  - apiGroups: 
      {{- toYaml .apiGroups | nindent 6 }}
    resources:
      {{- toYaml .resources | nindent 6 }}
    verbs: 
      {{- toYaml .verbs | nindent 6 }}
{{- end }}
{{- end }}
