{{- range $name, $config := .Values.secret}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: {{ $config.type | default "Opaque" }}
data: 
{{- range $key, $value := $config.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
