{{- range $name, $config := .Values.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $config.namespace | default $.Release.Namespace }}
  {{- if $config.annotations }}
  annotations:
    {{- toYaml $config.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $config.automountServiceAccountToken | default false }}
{{- end }}
